/**
 * Country (display name from frontend countries.js) → ISO 4217 currency code.
 * Anything not listed defaults to USD.
 */
const COUNTRY_TO_CURRENCY = {
  // South Asia
  'India':                       'INR',
  'Bangladesh':                  'BDT',
  'Pakistan':                    'PKR',
  'Sri Lanka':                   'LKR',
  'Nepal':                       'NPR',
  'Bhutan':                      'BTN',
  'Maldives':                    'MVR',
  'Afghanistan':                 'AFN',

  // South-East Asia
  'Singapore':                   'SGD',
  'Malaysia':                    'MYR',
  'Indonesia':                   'IDR',
  'Thailand':                    'THB',
  'Vietnam':                     'VND',
  'Philippines':                 'PHP',
  'Cambodia':                    'KHR',
  'Laos':                        'LAK',
  'Myanmar':                     'MMK',
  'Brunei':                      'BND',
  'Timor-Leste':                 'USD',

  // East Asia
  'China':                       'CNY',
  'Hong Kong':                   'HKD',
  'Macao':                       'MOP',
  'Taiwan':                      'TWD',
  'Japan':                       'JPY',
  'South Korea':                 'KRW',
  'North Korea':                 'KPW',
  'Mongolia':                    'MNT',

  // Middle East
  'United Arab Emirates':        'AED',
  'Saudi Arabia':                'SAR',
  'Qatar':                       'QAR',
  'Kuwait':                      'KWD',
  'Bahrain':                     'BHD',
  'Oman':                        'OMR',
  'Jordan':                      'JOD',
  'Lebanon':                     'LBP',
  'Israel':                      'ILS',
  'Palestine':                   'ILS',
  'Iran':                        'IRR',
  'Iraq':                        'IQD',
  'Syria':                       'SYP',
  'Yemen':                       'YER',
  'Turkey':                      'TRY',

  // Africa
  'Egypt':                       'EGP',
  'Morocco':                     'MAD',
  'Algeria':                     'DZD',
  'Tunisia':                     'TND',
  'Libya':                       'LYD',
  'Sudan':                       'SDG',
  'South Sudan':                 'SSP',
  'Ethiopia':                    'ETB',
  'Eritrea':                     'ERN',
  'Djibouti':                    'DJF',
  'Somalia':                     'SOS',
  'Kenya':                       'KES',
  'Uganda':                      'UGX',
  'Tanzania':                    'TZS',
  'Rwanda':                      'RWF',
  'Burundi':                     'BIF',
  'South Africa':                'ZAR',
  'Nigeria':                     'NGN',
  'Ghana':                       'GHS',
  'Senegal':                     'XOF',
  'Côte d\'Ivoire':              'XOF',
  'Burkina Faso':                'XOF',
  'Mali':                        'XOF',
  'Niger':                       'XOF',
  'Benin':                       'XOF',
  'Togo':                        'XOF',
  'Guinea-Bissau':               'XOF',
  'Cameroon':                    'XAF',
  'Chad':                        'XAF',
  'Gabon':                       'XAF',
  'Central African Republic':    'XAF',
  'Congo (Brazzaville)':         'XAF',
  'Equatorial Guinea':           'XAF',
  'Congo (Kinshasa)':            'CDF',
  'Angola':                      'AOA',
  'Mozambique':                  'MZN',
  'Zambia':                      'ZMW',
  'Zimbabwe':                    'USD',
  'Malawi':                      'MWK',
  'Botswana':                    'BWP',
  'Namibia':                     'NAD',
  'Lesotho':                     'LSL',
  'Eswatini':                    'SZL',
  'Madagascar':                  'MGA',
  'Mauritius':                   'MUR',
  'Seychelles':                  'SCR',
  'Comoros':                     'KMF',
  'Sierra Leone':                'SLL',
  'Liberia':                     'LRD',
  'Guinea':                      'GNF',
  'Gambia':                      'GMD',
  'Cabo Verde':                  'CVE',
  'São Tomé and Príncipe':       'STN',
  'Mauritania':                  'MRU',

  // Europe — Eurozone
  'Germany':                     'EUR',
  'France':                      'EUR',
  'Italy':                       'EUR',
  'Spain':                       'EUR',
  'Portugal':                    'EUR',
  'Netherlands':                 'EUR',
  'Belgium':                     'EUR',
  'Luxembourg':                  'EUR',
  'Austria':                     'EUR',
  'Ireland':                     'EUR',
  'Greece':                      'EUR',
  'Finland':                     'EUR',
  'Estonia':                     'EUR',
  'Latvia':                      'EUR',
  'Lithuania':                   'EUR',
  'Slovakia':                    'EUR',
  'Slovenia':                    'EUR',
  'Cyprus':                      'EUR',
  'Malta':                       'EUR',
  'Croatia':                     'EUR',
  'Andorra':                     'EUR',
  'Monaco':                      'EUR',
  'San Marino':                  'EUR',
  'Vatican City':                'EUR',
  'Montenegro':                  'EUR',
  'Kosovo':                      'EUR',

  // Europe — others
  'United Kingdom':              'GBP',
  'Switzerland':                 'CHF',
  'Liechtenstein':               'CHF',
  'Norway':                      'NOK',
  'Sweden':                      'SEK',
  'Denmark':                     'DKK',
  'Iceland':                     'ISK',
  'Poland':                      'PLN',
  'Czechia':                     'CZK',
  'Hungary':                     'HUF',
  'Romania':                     'RON',
  'Bulgaria':                    'BGN',
  'Albania':                     'ALL',
  'North Macedonia':             'MKD',
  'Serbia':                      'RSD',
  'Bosnia and Herzegovina':      'BAM',
  'Moldova':                     'MDL',
  'Ukraine':                     'UAH',
  'Belarus':                     'BYN',
  'Russia':                      'RUB',
  'Armenia':                     'AMD',
  'Azerbaijan':                  'AZN',
  'Georgia':                     'GEL',
  'Kazakhstan':                  'KZT',
  'Kyrgyzstan':                  'KGS',
  'Tajikistan':                  'TJS',
  'Turkmenistan':                'TMT',
  'Uzbekistan':                  'UZS',

  // Americas
  'United States':               'USD',
  'Canada':                      'CAD',
  'Mexico':                      'MXN',
  'Guatemala':                   'GTQ',
  'Belize':                      'BZD',
  'Honduras':                    'HNL',
  'El Salvador':                 'USD',
  'Nicaragua':                   'NIO',
  'Costa Rica':                  'CRC',
  'Panama':                      'PAB',
  'Cuba':                        'CUP',
  'Dominican Republic':          'DOP',
  'Haiti':                       'HTG',
  'Jamaica':                     'JMD',
  'Bahamas':                     'BSD',
  'Barbados':                    'BBD',
  'Trinidad and Tobago':         'TTD',
  'Saint Lucia':                 'XCD',
  'Saint Kitts and Nevis':       'XCD',
  'Saint Vincent and the Grenadines': 'XCD',
  'Antigua and Barbuda':         'XCD',
  'Dominica':                    'XCD',
  'Grenada':                     'XCD',
  'Brazil':                      'BRL',
  'Argentina':                   'ARS',
  'Chile':                       'CLP',
  'Uruguay':                     'UYU',
  'Paraguay':                    'PYG',
  'Bolivia':                     'BOB',
  'Peru':                        'PEN',
  'Colombia':                    'COP',
  'Venezuela':                   'VES',
  'Ecuador':                     'USD',
  'Guyana':                      'GYD',
  'Suriname':                    'SRD',

  // Oceania
  'Australia':                   'AUD',
  'New Zealand':                 'NZD',
  'Fiji':                        'FJD',
  'Papua New Guinea':            'PGK',
  'Solomon Islands':             'SBD',
  'Vanuatu':                     'VUV',
  'Samoa':                       'WST',
  'Tonga':                       'TOP',
  'Kiribati':                    'AUD',
  'Tuvalu':                      'AUD',
  'Nauru':                       'AUD',
  'Marshall Islands':            'USD',
  'Micronesia':                  'USD',
  'Palau':                       'USD',
};

function currencyForCountry(country) {
  if (!country) return 'USD';
  return COUNTRY_TO_CURRENCY[String(country).trim()] || 'USD';
}

module.exports = { COUNTRY_TO_CURRENCY, currencyForCountry };
